## @see https://git.io/gitpod
image: nberlette/gitpod-enhanced

## tasks
  # before:  runs on every start; good spot for: terminal configurations
  # init:    only on prebuilds;   good spot for: packages dependencies
  # command: runs on every start; good spot for: hot reload dev server
#
tasks:
  - init: pnpm install
    before: pnpm i -g vercel 

gitConfig:
  bash.showColorHints: "true"          # colorizes git info based on branch/upstream status
  bash.showUpstream: "auto"            # false | auto verbose name git svn (accepts > 1)
  bash.showUntrackedFiles: "false"     # % added if untracked files are detected
  bash.showStashState: "true"          # $ added if stashed files are detected
  bash.showDirtyState: "true"          # * added if tracked files are modified
  bash.hideIfPwdIgnored: "false"       # hides git prompt if cwd is in .gitignore
  init.defaultbranch: "main"
  color.ui: "auto"
  color.branch.current: "yellow reverse"
  color.branch.local: "yellow"
  color.branch.remote: "green"
  color.diff.meta: "yellow bold"
  color.diff.frag: "magenta bold"
  color.diff.old: "red bold"
  color.diff.new: "green bold"
  color.status.added: "yellow"
  color.status.changed: "green"
  color.status.untracked: "red"
  alias.bail: "reset HEAD --"
  alias.graph: "!git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative"
  alias.amend: "!git log -n 1 --pretty=tformat:%s%n%n%b | git commit -F - --amend"
  alias.setup: "!git init && git add . && git commit -m 'Initial commit.'"
  alias.nb: "!git branch | grep ^* | awk '{ print $2 }'"
  alias.cleanup: "!git ls-files -z --deleted | xargs -0 git rm"
  alias.addnew: "!git cleanup && git add . --all"
  url.https://github.com/.insteadof: "gh:"
  url.https://gist.github.com/.insteadof: "gist:"
  url.https://gitlab.com/.insteadof: "gl:"
  url.https://bitbucket.org/.insteadof: "bb:"

## vscode extensions to pre-install in workspace
vscode:
  extensions:
    - eamodio.gitlens
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
    - christian-kohler.npm-intellisense
    - eg2.vscode-npm-script
    - timonwong.shellcheck
    - mads-hartmann.bash-ide-vscode
    - gamunu.vscode-yarn

## workspace ports: how to handle upon opening
ports:
  - port: 3000
    onOpen: open-preview
    visibility: private
  - port: 5000
    onOpen: notify

## github prebuild preferences
github:
  prebuilds:
    master: true
    branches: true
    addLabel: true
    addCheck: true
    addBadge: true
